### ISSUE TITLE
Use regularization method in cond_rnn

### ISSUE THREAD

**Issue by Zekai-Wang** [philipperemy/cond_rnn#10]
Thank you so much for your work, very excellent library. I'm trying to use this library in my project, but I encounter a problem: I'd like to use regularizer method such as 'kernel_regularizer' in ConditionalRNN layer, but I found it can't support regularizer method in ConditionalRNN. I check the tensorflow document, it seems that "tf.keras.layers.rnn" doesn't have "kernel_regularizer" argument, so may I ask how to use regularizer in ConditionalRNN? Thanks
<img width="469" alt="Screen Shot 2020-10-26 at 7 52 19 PM" src="https://user-images.githubusercontent.com/57110403/97243819-24e64900-17c5-11eb-813e-805810c29549.png">
<img width="428" alt="Screen Shot 2020-10-26 at 7 55 21 PM" src="https://user-images.githubusercontent.com/57110403/97243855-37f91900-17c5-11eb-9ab6-092318223761.png">

**Comment by philipperemy** [comment]
@Zekai-Wang sorry for the wait. I pushed a new version that can handle all that: https://github.com/philipperemy/cond_rnn/commit/5db67929e7bcb1901bcbb20567be9c1848671689.
```
pip install cond-rnn --upgrade
```
