### ISSUE TITLE
Dummy stations example

### ISSUE THREAD

**Issue by ir0nt0ad** [philipperemy/cond_rnn#22]
https://github.com/philipperemy/cond_rnn/blob/b35616f0ec6ed2df3b1929b0a4fae8d34ca0e4bf/examples/dummy_stations_example.py#L13
First of all, thanks a lot for your work! Sorry I'm having trouble understanding parts of the code. We say `C` is the target, but I don't see `C` getting any special treatment further down; in fact, it appears we're predicting all of `A`,`B` and `C` for each timestep, since our `y` includes all of these values. Could you please let me know what's actually going on here?

**Comment by philipperemy** [comment]
@sh0gg0th good catch. The example was pretty big nonsense.
I updated it: https://github.com/philipperemy/cond_rnn/blob/master/examples/dummy_stations_example.py.
Let me know if it looks better.

**Comment by ir0nt0ad** [comment]
@philipperemy Yes this one is much more clear, and thanks a lot for your quick turnaround!

**Comment by philipperemy** [comment]
Welcome :)
