### ISSUE TITLE
Bidirectional LSTM

### ISSUE THREAD

**Issue by hoba87** [philipperemy/cond_rnn#25]
I would like to use your ConditionalRNN code with a bidirectional LSTM layer, e.g. like here [https://keras.io/examples/nlp/bidirectional_lstm_imdb/](https://keras.io/examples/nlp/bidirectional_lstm_imdb/).
Is this possible?

**Comment by philipperemy** [comment]
@hoba87 I'd say it's not currently possible but you can try to make it work. That would be really cool if you could make a PR :)

**Comment by AtrCheema** [comment]
@hoba87 did you find a way to do it?

**Comment by peterukk** [comment]
Did anyone try this?

**Comment by pepper-jk** [comment]
I was able to use condRNNs with LSTMs and GRUs for my bachelor thesis about a year ago.
So this works at least.

Not sure what the difference between a normal LSTM and a bidirectional LSTM is. So your mileage may vary.

But honestly I would just try it. That is what I did back then. :D

**Comment by peterukk** [comment]
Thanks. I didn't have any luck with using this package for bidirectional RNNs - probably possible with some tinkering - but turns out it was [fairly easy to write manual code that I believe does the same job as cond_rnn.](https://stackoverflow.com/questions/59402595/can-i-train-the-initial-hidden-state-of-a-rnn-to-represent-the-initial-condition) I'll share my code in case someone finds it useful:

```python
# shape(x_tr_m) = (nsamples, nseq, nx_main)
# shape(x_tr_s) = (nsamples, nx_aux)
# shape(y_tr)   = (nsamples, nseq, noutputs)
nx_aux = 2
nx_main = nx - nx_aux
# Main inputs associated with RNN layer (sequence dependent)
inputs = Input(shape=(None,nx_main),name='inputs_main')
# Auxiliary inputs that do not dependend on sequence
inp_aux = Input(shape=(nx_aux),name='inputs_aux')
# Target outputs: these are fed as part of the input to avoid problem with 
# validation data where TF complained about wrong shape
target  = Input((None,ny))

# aux input layer; this predicts the initial state of the RNN from the
# auxiliary inputs; the dense layer mapping transforms them into right shape
mlp_dense_inp = Dense(nneur, activation='relu',name='dense_inputs_aux')(inp_aux)
# The Bidirectional RNN layer
layer_rnn = layers.GRU(nneur,return_sequences=True)
hidden = layers.Bidirectional(layer_rnn, merge_mode=mergemode, name ='bidirectional')\
    (inputs, initial_state= [mlp_dense_inp,mlp_dense_inp])
# outputs
outputs = TimeDistributed(layers.Dense(ny, activation="sigmoid"),name='dense_output')(hidden)
#
model = Model(inputs=[inputs, inp_aux, target], outputs=outputs)
model.compile(optimizer='adam', loss='mse')
model.add_loss(CustomLoss(target,outputs))
model.summary()

# # Create earlystopper and possibly other callbacks
callbacks = [EarlyStopping(monitor='val_loss',  patience=patience, verbose=1, \
                             mode='min',restore_best_weights=True)]

# START TRAINING
history = model.fit(x=[x_tr_m, x_tr_aux, y_tr], y=None, epochs=epochs, batch_size=batch_size, \
            shuffle=True,  verbose=1, validation_data=[x_val_m, x_val_aux, y_val], callbacks=callbacks)  
```

**Comment by philipperemy** [comment]
@peterukk thanks for sharing!

**Comment by philipperemy** [comment]
For information, I solved the problem in ConditionalRNN 3.0. Make sure to update to the latest version:

```
pip install cond-rnn --upgrade
```

It was fixed in https://github.com/philipperemy/cond_rnn/commit/5e468aed4364236c7195c5ca37c93be9301a9aba.

I provide an example on how to use `Bidirectional` with this module here: https://github.com/philipperemy/cond_rnn/blob/master/examples/bidirect.py

**Comment by aymoawad** [comment]
Thanks, @philipperemy. Can you please provide an example of `Bidirectional` with functional API usage instead of a sequential model?

**Comment by philipperemy** [comment]
@aymoawad good question. I have just tried to port it with the functional API but somehow Keras does not make it very user friendly to do so. CondRNN expects inputs and conditions (a list) as input. When using the functional API, Keras takes the first input as the input for the Bidirectional layer and the second input is pushed to the initial state of the Bidirectional layer, which is pretty absurd.

**Comment by philipperemy** [comment]
For info.

**Disclaimer: Does not work yet**
```python
import numpy as np
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import GRU, Bidirectional

from cond_rnn import ConditionalRecurrent

forward_layer = ConditionalRecurrent(GRU(units=12, return_sequences=True))
backward_layer = ConditionalRecurrent(GRU(units=13, return_sequences=True, go_backwards=True))

NUM_SAMPLES = 100
TIME_STEPS = 10
INPUT_DIM = 3
NUM_CLASSES = 2

inputs = (
    Input(shape=(TIME_STEPS, INPUT_DIM)),
    Input(shape=(TIME_STEPS, INPUT_DIM))  # conditions.
)

outputs = Bidirectional(
    layer=forward_layer,
    backward_layer=backward_layer,
)(inputs=inputs)

model = Model(inputs=inputs, outputs=outputs)
model.compile(loss='categorical_crossentropy')

model.summary()

train_inputs = np.random.uniform(size=(NUM_SAMPLES, TIME_STEPS, INPUT_DIM))
train_targets = np.zeros(shape=[NUM_SAMPLES, NUM_CLASSES])
assert model.predict(x=[train_inputs, train_targets]).shape == (NUM_SAMPLES, 10, 12 + 13)
```

**Comment by aymoawad** [comment]
@philipperemy yes, I discovered the same thing as well. Not sure what is the logic behind having the second input moved to the initial state. I ended up passing a tuple instead of a list and that seems to work.

**Comment by aymoawad** [comment]
Btw, your example should work. It looks like your input layer does not have the right shapes though?
