### ISSUE TITLE
[QUESTION] how to predicting future unseen dataframe?

### ISSUE THREAD

**Issue by ichsan2895** [philipperemy/cond_rnn#30]
Hello, I have tried "lstm.py" example files.

In the example, the time start from 1995-01-01 until 2020-05-13.
Now, how to predict the unseen dataframe? Start from 2020-05-14 until desired time?

If I predict it with normal pure autoregressive GRU model. I was success. But, I dont know how to be predicting multivariate time series in the future? since I dont have any condition dataframe after 2020-05-13.

**Comment by philipperemy** [comment]
@ichsan2895 I see what you mean. I didn't write the "lstm.py" code but what I can tell you is if your model predicts one step at a time. You have to predict t+1 and use this prediction to predict t+2 and so on.

**Comment by ichsan2895** [comment]
> You have to predict t+1 and use this prediction to predict t+2 and so on.

Sorry for late reply. Do you have any reference and code about that?

**Comment by philipperemy** [comment]
@ichsan2895 I think this link is a good beginning: https://machinelearningmastery.com/time-series-prediction-lstm-recurrent-neural-networks-python-keras/.

Familiarize yourself first with LSTM then you can easily swap the LSTM class with the TCN class.

Good luck.

**Comment by philipperemy** [comment]
Note that it's from 2016 the link but most of it is still very relevant as of today.
