### ISSUE TITLE
[QUESTION] Difference between ConditionalRNN and Other Approach

### ISSUE THREAD

**Issue by fjpa121197** [philipperemy/cond_rnn#32]
Hi,

First of all, thanks for the package that allows to use time series data (time variant) with time invariant data (conditions). I think there are a lot of cases/scenarios where both types of data are needed to use at same time.

I'm having a similar situation, where I want to use both types of data, where I have my time series data and currently using a LSTM and I have my conditions (time invariant features) and want to incorporate them into the problem. 

Obviously, the most straight forward solution was to duplicate the conditions into the time series, and have them not change over time. I had no problem doing this, and it did boost my performance a lot (compared to only using conditions/time invariant features alone), however, I also read some papers which share the thought on not doing that combination, because it pollute the time variant information with time invariant data and it might just create a harder problem to solve.

I did read in other papers to not used the above approach, one of them was to modify/specify the hidden state an initial step and feed the time invariant into it. And I was trying to do this in my own (I did not find your package before that) and come up with the following model definition (example):

```python
lstm_input = keras.Input(
    shape=(3,3), name="lstm_input"
)  # Variable-length sequence of ints
pre_go_live_input_hidden_states = keras.Input(shape=(3,), name="pre-go-live")  # Variable-length sequence of ints


pre_go_live_fc_layer_1 = keras.layers.Dense(50, activation='relu')(pre_go_live_input_hidden_states)
# Reduce sequence of embedded words in the title into a single 128-dimensional vector
lstm_features = LSTM(50)
outputs = lstm_features(lstm_input, initial_state=[pre_go_live_fc_layer_1,pre_go_live_fc_layer_1])

# Stick a department classifier on top of the features
pred = keras.layers.Dense(1, name="prediction_layer")(outputs)

# Instantiate an end-to-end model predicting both priority and department
model = keras.Model(
    inputs=[lstm_input, pre_go_live_input_hidden_states],
    outputs=[pred]
)
```
Here, my conditions are the pre_go_live_input_hidden_states variable, which need a Dense layer afterwards to reduce the data to 50, so it can be added to the initial_state of the LSTM (ignore the part that I'm also passing the cell state initial values).

My question is regarding the difference between the previous model definition, and how ConditionalRNN works behind scenes? Is it similar to it? 

I'm having trouble understanding the ConditionalRecurrent class, mostly around the treatment giving to the conditions input.

My current time series data is in the following shape: (29000, 7, 14). And my conditions data shape is: (29000,124), which of those 124 features, some of them are encoded variables and numerical variables.

Is it possible to use your package, and still use the 124 conditions to initialize the hidden state at initial step?

Thanks,
Francisco Parrilla A

**Comment by fjpa121197** [comment]
![image](https://user-images.githubusercontent.com/43655840/180723906-fe88ab8d-c8f7-4c98-9bd9-23c8b144c5e2.png)

I think the above image tells me the difference. 

Each condition has it's own input and processing before being concatenated and fed into the LSTM hidden state? If I only define 1 condition, which has multiple characteristics/features of my object (combination on one hot encoded variables and numerical variables), it will be different if I divided them into, lets say, category of features, and feed them separately as a list of conditions instead. Is this reasoning correct?

**Comment by philipperemy** [comment]
@fjpa121197 There's a discussion about your question here: https://github.com/philipperemy/cond_rnn/issues/3.

- Each condition has it's own input and processing before being concatenated and fed into the LSTM hidden state?
> yes that's correct.

- If I only define 1 condition, which has multiple characteristics/features of my object (combination on one hot encoded variables and numerical variables), it will be different if I divided them into, lets say, category of features, and feed them separately as a list of conditions instead. Is this reasoning correct?
> yes that's correct. I need to do the math if it makes any difference in practice or not (linear algebra) but it was more conceptual when I wrote this lib. I didn't want to mix the conditions together. But for example, if you concat the conditions and multiply by weights W then I guess it's the same things as having two weights W1 and W2 and multiply each condition by its corresponding W. I guess in your example, you can just consider one condition composed of 124 values and it will work just fine.

**Comment by philipperemy** [comment]
Multi cond case. With the tensor shapes.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/4516927/181231844-b51e8286-7510-45aa-9b41-8df77748e970.png">

**Comment by philipperemy** [comment]
Single condition case.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/4516927/181232844-0bea8506-319d-486f-90d2-e9ff35111ff7.png">

**Comment by philipperemy** [comment]
In the example, if you merge c1.shape = (1,4) and c2.shape = (1,3) into c.shape = (1,7), the weight matrix will be W.shape = (7,50) and the bias will be bias.shape = (50,). So the only difference is the possibility to have different bias b1 and b2 in the multi condition case. In the single condition case, there's only one b. So I guess if the conditions are centered differently (for example one has a mean of 0.5 and the other one 0.0, then it might be a problem).

**Comment by philipperemy** [comment]
I hope all those points will answer your questions!

**Comment by fjpa121197** [comment]
Just one last question. In my first post, I showed a code snippet that initializes the hidden state with a condition.

This is a different one, but still follows the same approach (I think):

```python
# Define inputs of the model
post_go_live_input = keras.Input(shape=(7,14), name="post_go_live")
pre_go_live_input_hidden_state = keras.Input(shape=(263,), name="pre-go-live_hidden")


# Define layers for each type of input - LSTM for lstm input and FCL for pre-go-live input
fc_features_layer1 = keras.layers.Dense(50, activation='relu')(pre_go_live_input_hidden_state)
lstm_features = LSTM(50,activation='relu')

outputs = lstm_features(post_go_live_input, initial_state=[fc_features_layer1,tf.zeros_like(fc_features_layer1)])

pred = keras.layers.Dense(1, name="prediction_layer")(outputs)

# Instantiate an end-to-end model predicting both priority and department
model = keras.Model(
    inputs=[post_go_live_input, pre_go_live_input_hidden_state],
    outputs=[pred]
)
```

If I decide to treat all features as one condition, which has 263 features, will the following code be similar to your implementation?

Does your implementation touches/alters the cell state?

Thanks for the help

**Comment by philipperemy** [comment]
Yes your code is very similar to my implementation. 

`initial_state[0]` points to `init_h` and `initial_state[1]` to `init_c`. 
From: https://github.com/keras-team/keras/blob/master/keras/layers/rnn/lstm.py#L654
I guess you don't need to pass `tf.zeros_like(fc_features_layer1)` to `initial_state`. By default it should be filled with 0.

Does your implementation touches/alters the cell state?
It's not doing more than what your implementation already does. 
Except that the `ConditionalRecurrent` is a "Keras valid" wrapper.

**Comment by fjpa121197** [comment]
I will try not passing anything to the cell_state, I saw in one SO question that it was needed, even if it was all 0's. 

Thanks for the help! I will stick to your implementation, I really like the idea of separating conditions, which I kind of see it, as a way to separate types of features (it can be based on domain knowledge, or data types).

**Comment by philipperemy** [comment]
Awesome good luck in your journey!
