### ISSUE TITLE
Basic conditional LSTM

### ISSUE THREAD

**Issue by Simo-JDev** [philipperemy/cond_rnn#36]
Hello,

I currently have a very basic LSTM NN, which predicts the next array of n_features, from the past 10 time steps, i.e.
```python

model = Sequential()
model.add(LSTM(n_lookback, input_shape=(n_lookback, n_features)))
model.add(Dense(n_features))
model.compile()
```

where n_features is the number of features in each tilmestep and n_lookback is the number of previous time steps provided to the LSTM.
Since I am trying to also add conditions that are not time dependent, I thought I'd try your cond_RNN.
I am having some issues starting out though, since the example are a bit to complex for me, I have only started a few months ago working with NN and Keras. 
The condition would be a float, i.e. a value of a physical property, such as 3.1 or 4.5 etc.
Could you offer any help on how to start out?

Thanks in advance. You have already been so helpful with he MacOS import issue 😊

**Comment by philipperemy** [comment]
@JustDonuts Welcome 😊

> where n_features is the number of features in each tilmestep and n_lookback is the number of previous time steps provided to the LSTM.

The first input to the LSTM is the number of units and not the number of previous time steps. You can't give the number of previous steps as a parameter to the LSTM. The longer your sequence is, the more units you should add to your LSTM. You will see that most people choose 64, 128, 256, 512 and 1024. Check the LSTM Keras documentation to learn more about it.

> The condition would be a float, i.e. a value of a physical property, such as 3.1 or 4.5 etc.
Could you offer any help on how to start out?

What you're looking for is in this example:

https://github.com/philipperemy/cond_rnn/blob/b0597bd4569bb0454abd96a2750adbb170e4a439/examples/single_cond_example.py#L10

But if you are not very familiar with the Keras framework, I strongly advise you to learn more about it before you start to use some more advanced packages like this one!

**Comment by philipperemy** [comment]
@JustDonuts I'll close this thread for now. Feel free to re-open it if it was not clear enough. Thanks!
