### ISSUE TITLE
Embeding Layer with ConditionalRecurrent

### ISSUE THREAD

**Issue by alexandreib** [philipperemy/cond_rnn#37]
Hi,

First thanks for this great library, it's very usefull and inspiring.

I'm wondering, if using an embeding layer before the Conditionnal reccurent layers could have a limitation ?
I tried it and it was working. 

I just want to make sure from your point of view if I don't miss anything.

Thanks,
Alexandre

**Comment by philipperemy** [comment]
@alexandreib Hi! Thanks for the feedback! Much appreciated.

The embedding layer is a different representation of the data. It retains the information (hopefully).

So I don't see any problem to add one before it.

Thanks
Philippe

**Comment by alexandreib** [comment]
Thanks Philippe!

**Comment by philipperemy** [comment]
Welcome Alexandre!
