### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sshafiei-tech** [philipperemy/cond_rnn#43]
Hi, I tried to install the conditional rnn but it failed. Bellow is the error:
pip install cond-rnn
Collecting cond-rnn
  Using cached cond-rnn-3.2.1.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by philipperemy** [comment]
@sshafiei-tech can you share more?
```
╰─> [8 lines of output]
```

**Comment by sshafiei-tech** [comment]
Dear Philippe,
Thank you for your email. As you advised, I tried to install the module via
git instead of pip, and it worked fine. I also had to apply the below minor
change:
Original: long_description=open('README.md').read(),
Revised: long_description = open('README.md', encoding='utf-8').read(),

All is good from my side, and thank you again for sharing your scripts.

Kind regards,
Sajjad

**Comment by philipperemy** [comment]
I pushed 3.2.2 with your fix. Thank you!
