### ISSUE TITLE
kwargs for tf.keras.layers.RNN

### ISSUE THREAD

**Issue by rolandsz** [philipperemy/cond_rnn#7]
Hi,

I've just started to use cond_rnn and I'm trying to replace LSTM layers in my model with ConditionalRNN. 

The README says that one should be able to use keywords like return_sequences.
> *args, **kwargs: Any parameters of the tf.keras.layers.RNN class, such as return_sequences, return_state, stateful, unroll...

However, since be1e97fa74ee06ef44e6dec1de8eb662b63004b9 ConditionalRNN derives from tf.keras.layers.Layer which prohibits the usage of these kwargs, as only the following kwargs are allowed for tf.keras.layers.Layer:
- input_shape
- batch_input_shape
- batch_size
- weights
- activity_regularizer
- autocast

Due to the `super().__init__(**kwargs)` call, keywords for the RNN layer are considered to be invalid and an exception is raised.

My environment:
>tensorflow==2.1.0
Keras==2.3.1
cond-rnn==2.1

**Comment by philipperemy** [comment]
Hey @rolandsz thanks for reporting. I fixed it in https://github.com/philipperemy/cond_rnn/commit/4a1e95a6b53f599d1e6928c2fb33e0bcc27e9926.

```
pip install cond-rnn --upgrade
```
