### ISSUE TITLE
Non-issue: fix exception message

### ISSUE THREAD

**Issue by oneiroid** [philipperemy/cond_rnn#9]
https://github.com/philipperemy/cond_rnn/blob/c555fd9d93929cf6b187c68a24c4ba28e278b3be/cond_rnn/cond_rnn.py#L56

As titled, non-issue, but still I spent couple of minutes trying to figure out what "\nor" means. Is it negating OR? )))
Either remove carriage return or put initial_cond_shape inside the exception message string manually.
In your case repr of tuple ("msg", initial_cond_shape) is being printed which does escaped chars and not parsed.

**Comment by philipperemy** [comment]
I've deleted the \n ;)
